version: '2'
services:
 mysql:
   image: mysql:5.5
   ports: 
    - "3306:3306"
   container_name: mysql-docker
   network_mode: host
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: matchdb
     MYSQL_USER: app_root
     MYSQL_PASSWORD: root123
 userauth-app:
   image: userauth-app
   build: userservice/
   restart: always
   network_mode: host
   depends_on: 
    - mysql
   ports: 
    - "8089:8089"

 match-app:
   image: match-app
   build: favouriteservice/
   restart: always
   network_mode: host
   depends_on: 
    - mysql
   ports: 
    - "8080:8080"
 angular-match:
   image: matchui-app
   build: CMatchesUI/
   network_mode: host
   container_name: match-angular-docker
   ports: 
    - "4200:4200"
